//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RThomaz.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RThomaz.Web.Resources.ContaResource", typeof(ContaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string AtivoFalseTitle {
            get {
                return ResourceManager.GetString("AtivoFalseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta ativa.
        /// </summary>
        public static string AtivoTitle {
            get {
                return ResourceManager.GetString("AtivoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string AtivoTrueTitle {
            get {
                return ResourceManager.GetString("AtivoTrueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        public static string ControllerTitle {
            get {
                return ResourceManager.GetString("ControllerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um Grupo de Conta.
        /// </summary>
        public static string DropDownGrupoContaDefaultOption {
            get {
                return ResourceManager.GetString("DropDownGrupoContaDefaultOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Conta.
        /// </summary>
        public static string FilterGrupoContaTitle {
            get {
                return ResourceManager.GetString("FilterGrupoContaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Conta.
        /// </summary>
        public static string FilterTipoContaTitle {
            get {
                return ResourceManager.GetString("FilterTipoContaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Conta.
        /// </summary>
        public static string GrupoContaTitle {
            get {
                return ResourceManager.GetString("GrupoContaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações da Conta.
        /// </summary>
        public static string LegendDefault {
            get {
                return ResourceManager.GetString("LegendDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações de Abertura.
        /// </summary>
        public static string LegendSaldoAbertura {
            get {
                return ResourceManager.GetString("LegendSaldoAbertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string NomeTitle {
            get {
                return ResourceManager.GetString("NomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Conta Cartão de Crédito.
        /// </summary>
        public static string NovoContaCartaoCreditoTitle {
            get {
                return ResourceManager.GetString("NovoContaCartaoCreditoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Conta Cobrança Bancária.
        /// </summary>
        public static string NovoContaCobrancaBancariaTitle {
            get {
                return ResourceManager.GetString("NovoContaCobrancaBancariaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Conta Corrente.
        /// </summary>
        public static string NovoContaCorrenteTitle {
            get {
                return ResourceManager.GetString("NovoContaCorrenteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Conta Dinheiro.
        /// </summary>
        public static string NovoContaDinheiroTitle {
            get {
                return ResourceManager.GetString("NovoContaDinheiroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Conta Investimento.
        /// </summary>
        public static string NovoContaInvestimentoTitle {
            get {
                return ResourceManager.GetString("NovoContaInvestimentoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Conta Poupança.
        /// </summary>
        public static string NovoContaPoupancaTitle {
            get {
                return ResourceManager.GetString("NovoContaPoupancaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listagem de Contas.
        /// </summary>
        public static string PageIndexTitle {
            get {
                return ResourceManager.GetString("PageIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Abertura.
        /// </summary>
        public static string SaldoAberturaDataTitle {
            get {
                return ResourceManager.GetString("SaldoAberturaDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Inicial.
        /// </summary>
        public static string SaldoAberturaValorTitle {
            get {
                return ResourceManager.GetString("SaldoAberturaValorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Conta.
        /// </summary>
        public static string TipoContaTitle {
            get {
                return ResourceManager.GetString("TipoContaTitle", resourceCulture);
            }
        }
    }
}
